/** @file
  GUID for CompalLearningPkg PCD Token Space.
**/
#ifndef _COMPALLEARNINGPKG_TOKEN_SPACE_GUID_H_
#define _COMPALLEARNINGPKG_TOKEN_SPACE_GUID_H_

#define COMPALLEARNINGPKG_TOKEN_SPACE_GUID \
  { \
    0x97B5561C, 0x58CA, 0x4B8D, {0xA0, 0x88, 0x78, 0xD5, 0xCA, 0x38, 0x30, 0xF6} \
  }
extern EFI_GUID gCompalLearningPkgSpaceGuid;
#endif //_COMPALLEARNINGPKG_TOKEN_SPACE_GUID_H_
